<?php
/**
 * Language labels for database tables/fields belonging to extension "x4epublication"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'tx_x4epublication_category_main' => 'Publikationen - Main categories',
		'tx_x4epublication_category_main.title' => 'Title',
		'tx_x4epublication_category_sub' => 'Publikationen - Sub categories',
		'tx_x4epublication_category_sub.title' => 'Title',
		'tx_x4epublication_category_sub.title_plural' => 'Title (plural)',
		'tx_x4epublication_category_sub.cat_main' => 'Main category',
		'tx_x4epublication_category_sub.show_columns' => 'Columns',
		'tx_x4epublication_publication' => 'Publikationen - Publications',
		'tx_x4epublication_publication.category_sub' => 'Category',
		'tx_x4epublication_publication.authors' => 'Internal persons',
		'tx_x4epublication_publication.authors_ext' => 'External persons (Name, Firstname (LineBreak) Name, Firstname...)',
		'tx_x4epublication_publication.publishers' => 'Publishers',
		'tx_x4epublication_publication.publishers_ext' => 'Externe Herausgeber (Name, Vorname (Zeilenumbruch) Name, Vorname...)',
		'tx_x4epublication_publication.title' => 'Title',
		'tx_x4epublication_publication.location' => 'Location',
		'tx_x4epublication_publication.run' => 'Run',
		'tx_x4epublication_publication.year' => 'Year of publication',
		'tx_x4epublication_publication.volume' => 'Title and band',
		'tx_x4epublication_publication.magazine_title' => 'Magazin title',
		'tx_x4epublication_publication.magazine_year' => 'Magazine year',
		'tx_x4epublication_publication.magazine_issue' => 'Magazine issue',
		'tx_x4epublication_publication.abstract' => 'Abstract',
		'tx_x4epublication_publication.anthology_title' => 'Anthology title',
		'tx_x4epublication_publication.anthology_publisher' => 'Anthology publisher',
		'tx_x4epublication_publication.keywords' => 'Keywords',
		'tx_x4epublication_publication.jel_classification' => 'JEL-Classification',
		'tx_x4epublication_publication.file_ref' => 'File',
		'tx_x4epublication_publication.pages' => 'Pages',
		'tx_x4epublication_publication.event_date' => 'Event/Date',
		'tx_x4epublication_publication.other_redaction' => 'Other Redaction',
		'tx_x4epublication_publication.impact' => 'Impact',
		'tx_x4epublication_publication.publ_company' => 'Verlagsname/Auftraggeber',
		'tt_content.list_type_pi1' => 'Publications view',
		'tt_content.list_type_pi2' => 'Publications entry',
		'tt_content.list_type_publselect' => 'Publication selection',
		'tx_x4epublication_publication.url' => 'URL',
		'tx_x4epublication_publication.auth_publ.I.0' => 'Authors',
		'tx_x4epublication_publication.auth_publ.I.1' => 'Publishers',
		'tx_x4epublication_publication.auth_publ' => 'Authors or publisher',
		'tx_x4epublication_publication.daymonth' => 'Day and month (dd.mm.)',
		'tx_x4epublication_publication.pub_language' => 'Language',
		'tx_x4epublication_publication.description' => 'Description',

	),
	'de' => Array (
		'tx_x4epublication_category_main' => 'Publikationen - Hauptkategorien',
		'tx_x4epublication_category_main.title' => 'Titel',
		'tx_x4epublication_category_sub.title_plural' => 'Titel (plural)',
		'tx_x4epublication_category_sub' => 'Publikationen - Unterkategorien',
		'tx_x4epublication_category_sub.title' => 'Titel',
		'tx_x4epublication_category_sub.cat_main' => 'Hauptkategorie',
		'tx_x4epublication_category_sub.show_columns' => 'Columns',
		'tx_x4epublication_publication' => 'Publikationen - Publikationen',
		'tx_x4epublication_publication.category_sub' => 'Publikationstyp',
		'tx_x4epublication_publication.authors' => 'Interne Personen',
		'tx_x4epublication_publication.authors_ext' => 'Externe Personen (Name, Vorname (Zeilenumbruch) Name, Vorname...)',
		
		'tx_x4epublication_publication.publishers' => 'Herausgeber',
		'tx_x4epublication_publication.title' => 'Titel',
		'tx_x4epublication_publication.location' => 'Ort',
		'tx_x4epublication_publication.run' => 'Auflage',
		'tx_x4epublication_publication.year' => 'Erscheinungsjahr',
		'tx_x4epublication_publication.volume' => 'Reihentitel und Band',
		'tx_x4epublication_publication.magazine_title' => 'Zeitschriftentitel',
		'tx_x4epublication_publication.magazine_year' => 'Zeitschriftenjahrgang',
		'tx_x4epublication_publication.magazine_issue' => 'Zeitschriftenheft',
		'tx_x4epublication_publication.abstract' => 'Abriss',
		'tx_x4epublication_publication.anthology_title' => 'Sammelbandtitel (auch Lexikontitel)',
		'tx_x4epublication_publication.anthology_publisher' => 'Herausgeber des Sammelbands',
		'tx_x4epublication_publication.keywords' => 'Stichwörter',
		'tx_x4epublication_publication.jel_classification' => 'JEL-Klassifikation',
		'tx_x4epublication_publication.file_ref' => 'Datei',
		'tx_x4epublication_publication.pages' => 'Seiten',
		'tx_x4epublication_publication.event_date' => 'Anlass/Datum',
		'tx_x4epublication_publication.other_redaction' => 'Andere Ausgabe',
		'tt_content.list_type_pi1' => 'Publikationen - Ansicht',
		'tt_content.list_type_pi2' => 'Publikationen - Eingabe',
		'tt_content.list_type_publselect' => 'Publikationen - Auswahl',
		'tx_x4epublication_publication.auth_publ.I.0' => 'Autoren',
		'tx_x4epublication_publication.auth_publ.I.1' => 'Herausgeber',
		'tx_x4epublication_publication.auth_publ' => 'Autoren oder Herausgeber',
		'tx_x4epublication_publication.url' => 'URL',
		'tx_x4epublication_publication.daymonth' => 'Tag und Monat (dd.mm.)',
		'tx_x4epublication_publication.pub_language' => 'Sprache',
		'tx_x4epublication_publication.description' => 'Beschreibung',
	),
);
?>