<?php
/**
 * Language labels for plugin "tx_publics_pi1"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'listFieldHeader_category_sub' => 'Category',
		'listFieldHeader_authors' => 'Authors',
		'listFieldHeader_authors_ext' => 'External Authors (Name, Firstname (LineBreak) Name, Firstname...)',
		'listFieldHeader_publishers' => 'Publishers',
		'listFieldHeader_publishers_ext' => 'External Publishers  (Name, Firstname (LineBreak) Name, Firstname...)',
		'listFieldHeader_title' => 'Title',
		'listFieldHeader_location' => 'Location',
		'listFieldHeader_run' => 'Run',
		'listFieldHeader_year' => 'Year of publication',
		'listFieldHeader_volume' => 'Title and band',
		'listFieldHeader_magazine_title' => 'Magazin title',
		'listFieldHeader_magazine_year' => 'Magazine year',
		'listFieldHeader_magazine_issue' => 'Magazine issue',
		'listFieldHeader_anthology_title' => 'Anthology title',
		'listFieldHeader_anthology_publisher' => 'Anthology publisher',
		'listFieldHeader_pages' => 'Pages',
		'listFieldHeader_event_date' => 'Event/Date',
		'listFieldHeader_other_redaction' => 'Other Redaction',
		'list_mode_1' => 'Mode 1',
		'list_mode_2' => 'Mode 2',
		'list_mode_3' => 'Mode 3',
		'back' => 'Back',
		'pi_list_browseresults_prev' => '< Previous',
		'pi_list_browseresults_page' => 'Page',
		'pi_list_browseresults_next' => 'Next >',
		'pi_list_browseresults_displays' => 'Displaying results ###FROM### to ###TO### out of ###OUT_OF###',
		'pi_list_searchBox_search' => 'Search',
		'pi_list_browseresults_first' => '<< First',
		'pi_list_browseresults_last' => 'Last >>',
		'editRecord' => '<img src="fileadmin/histsem/_templates/images/icon_edit.gif" height="9" width="9"> Edit',
		'removeRecord' => '<img src="fileadmin/histsem/_templates/images/icon_delete.gif" height="9" width="9"> Remove',
		'pdfLinkText' => 'Get list as pdf',
		'txtLinkText' => 'Get list as text (rtf)',
		'createPublication' => 'Create publication',
		'noResultFound' => 'No results found',
		'searchLabel' => 'Suche',
		'publicationLabel' => 'Publikationstyp:',
		'allLabel' => 'Alle',
		'titleLabel' => 'Titel:',
		'authorLabel' => 'Autor:',
		'publYearLabel' => 'Publikationsjahr:',
		'fromLabel' => 'von:',
		'toLabel' => 'bis:',
		'pubLanguageLabel' => 'Sprache:',
	),
	'en' => Array(
		'listFieldHeader_category_sub' => 'Category',
		'listFieldHeader_authors' => 'Authors',
		'listFieldHeader_authors_ext' => 'External Authors (Name, Firstname (LineBreak) Name, Firstname...)',
		'listFieldHeader_publishers' => 'Publishers',
		'listFieldHeader_publishers_ext' => 'External Publishers  (Name, Firstname (LineBreak) Name, Firstname...)',
		'listFieldHeader_title' => 'Title',
		'listFieldHeader_location' => 'Location',
		'listFieldHeader_run' => 'Run',
		'listFieldHeader_year' => 'Year of publication',
		'listFieldHeader_volume' => 'Title and band',
		'listFieldHeader_magazine_title' => 'Magazin title',
		'listFieldHeader_magazine_year' => 'Magazine year',
		'listFieldHeader_magazine_issue' => 'Magazine issue',
		'listFieldHeader_anthology_title' => 'Anthology title',
		'listFieldHeader_anthology_publisher' => 'Anthology publisher',
		'listFieldHeader_pages' => 'Pages',
		'listFieldHeader_event_date' => 'Event/Date',
		'listFieldHeader_other_redaction' => 'Other Redaction',
		'list_mode_1' => 'Mode 1',
		'list_mode_2' => 'Mode 2',
		'list_mode_3' => 'Mode 3',
		'back' => 'Back',
		'pi_list_browseresults_prev' => '< Previous',
		'pi_list_browseresults_page' => 'Page',
		'pi_list_browseresults_next' => 'Next >',
		'pi_list_browseresults_displays' => 'Displaying results ###FROM### to ###TO### out of ###OUT_OF###',
		'pi_list_searchBox_search' => 'Search',
		'pi_list_browseresults_first' => '<< First',
		'pi_list_browseresults_last' => 'Last >>',
		'editRecord' => '<img src="fileadmin/histsem/_templates/images/icon_edit.gif" height="9" width="9"> Edit',
		'removeRecord' => '<img src="fileadmin/histsem/_templates/images/icon_delete.gif" height="9" width="9"> Remove',
		'pdfLinkText' => 'Get list as pdf',
		'txtLinkText' => 'Get list as text (rtf)',
		'createPublication' => 'Create publication',
		'noResultFound' => 'No results found',
		'searchLabel' => 'Search',
		'publicationLabel' => 'Publication type:',
		'allLabel' => 'All',
		'titleLabel' => 'Title:',
		'authorLabel' => 'Author:',
		'publYearLabel' => 'Publication year:',
		'fromLabel' => 'from:',
		'toLabel' => 'to:',
		'pubLanguageLabel' => 'Language:',
	),
	'de' => Array (
		'listFieldHeader_category_sub' => 'Kategorie',
		'listFieldHeader_authors' => 'Autoren',
		'listFieldHeader_authors_ext' => 'Externe Autoren (Name, Vorname (LineBreak) Name, Vorname...)',
		'listFieldHeader_publishers' => 'Herausgeber',
		'listFieldHeader_publishers_ext' => 'Externe Herausgeber  (Name, Vorname (LineBreak) Name, Vorname...)',
		'listFieldHeader_title' => 'Titel',
		'listFieldHeader_location' => 'Ort',
		'listFieldHeader_run' => 'Auflage',
		'listFieldHeader_year' => 'Publikationsjahr',
		'listFieldHeader_volume' => 'Titel und Band',
		'listFieldHeader_magazine_title' => 'Titel des Magazins',
		'listFieldHeader_magazine_year' => 'Jahr des Magazins',
		'listFieldHeader_magazine_issue' => 'Thema des Magazins',
		'listFieldHeader_anthology_title' => 'Titel des Sammelbandes',
		'listFieldHeader_anthology_publisher' => 'Herausgeber des Sammelbandes',
		'listFieldHeader_pages' => 'Seiten',
		'listFieldHeader_event_date' => 'Event/Datum',
		'listFieldHeader_other_redaction' => 'Andere Redaktion',
		'list_mode_1' => 'Modus 1',
		'list_mode_2' => 'Modus 2',
		'list_mode_3' => 'Modus 3',
		'back' => 'Zurück',
		'pi_list_browseresults_prev' => '< Zurück',
		'pi_list_browseresults_page' => '',
		'pi_list_browseresults_next' => 'Nächste >',
		'pi_list_browseresults_displays' => 'Zeige Resultate ###FROM###-###TO### von ###OUT_OF### Publikationen',
		'pi_list_searchBox_search' => 'Suche',
		'pi_list_browseresults_first' => '<< Anfang',
		'pi_list_browseresults_last' => 'Ende >>',
		'editRecord' => '<img src="fileadmin/histsem/_templates/images/icon_edit.gif" height="9" width="9"> Bearbeiten',
		'removeRecord' => '<img src="fileadmin/histsem/_templates/images/icon_delete.gif" height="9" width="9"> L&ouml;schen',
		'pdfLinkText' => 'Liste als PDF-Datei herunterladen',
		'txtLinkText' => 'Liste als RTF-Datei herunterladen',
		'createPublication' => 'Publikation erfassen',
		'noResultFound' => 'Es konnten keine entsprechenden Resultate gefunden werden',
		'searchLabel' => 'Suche',
		'publicationLabel' => 'Publikationstyp:',
		'allLabel' => 'Alle',
		'titleLabel' => 'Titel:',
		'authorLabel' => 'Autor:',
		'publYearLabel' => 'Publikationsjahr:',
		'fromLabel' => 'von:',
		'toLabel' => 'bis:',
		'pubLanguageLabel' => 'Sprache:',
	),
	'fr' => Array (
		'listFieldHeader_category_sub' => 'Catégorie',
		'listFieldHeader_authors' => 'Auteurs',
		'listFieldHeader_authors_ext' => 'Auteurs externes (Nom, Prenom (LineBreak) Nom, Prenom...)',
		'listFieldHeader_publishers' => 'Editeur',
		'listFieldHeader_publishers_ext' => 'Editeurs externes (Nom, Prenom (LineBreak) Nom, Prenom...)',
		'listFieldHeader_title' => 'Titre',
		'listFieldHeader_location' => 'Lieu',
		'listFieldHeader_run' => 'Edition',
		'listFieldHeader_year' => 'Année de publication',
		'listFieldHeader_volume' => 'Titre et bande',
		'listFieldHeader_magazine_title' => 'Titre du magazin',
		'listFieldHeader_magazine_year' => 'Année du magazin',
		'listFieldHeader_magazine_issue' => 'Sujet du magazin',
		'listFieldHeader_anthology_title' => 'Titre du recueil',
		'listFieldHeader_anthology_publisher' => 'Editeur du recueil',
		'listFieldHeader_pages' => 'Pages',
		'listFieldHeader_event_date' => 'Evénement/Date',
		'listFieldHeader_other_redaction' => 'Autres rédactions',
		'list_mode_1' => 'Mode 1',
		'list_mode_2' => 'Mode 2',
		'list_mode_3' => 'Mode 3',
		'back' => 'Arriére',
		'pi_list_browseresults_prev' => '< Arriére',
		'pi_list_browseresults_page' => '',
		'pi_list_browseresults_next' => 'Prochains >',
		'pi_list_browseresults_displays' => 'Montre resultats ###FROM###-###TO### de ###OUT_OF### publications',
		'pi_list_searchBox_search' => 'Recherche',
		'pi_list_browseresults_first' => '<< Début',
		'pi_list_browseresults_last' => 'Fin >>',
		'editRecord' => '<img src="fileadmin/histsem/_templates/images/icon_edit.gif" height="9" width="9"> Editer',
		'removeRecord' => '<img src="fileadmin/histsem/_templates/images/icon_delete.gif" height="9" width="9"> Supprimer',
		'pdfLinkText' => 'Télechargement de la liste en format PDF',
		'txtLinkText' => 'Télechargement de la liste en format RTF',
		'createPublication' => 'Ficher une publication',
		'noResultFound' => 'Votre recherche n\'a pas donne des resultats',
		'searchLabel' => 'Recherche',
		'publicationLabel' => 'Type de Publication:',
		'allLabel' => 'Tous',
		'titleLabel' => 'Titre:',
		'authorLabel' => 'Auteur:',
		'publYearLabel' => 'Année de parution:',
		'fromLabel' => 'de:',
		'toLabel' => 'jusque à:',
		'pubLanguageLabel' => 'langue: ',
	),
	'it' => Array (
		'listFieldHeader_category_sub' => 'Categoria',
		'listFieldHeader_authors' => 'Autori',
		'listFieldHeader_authors_ext' => 'Autori esterni (Cognome, Nome (LineBreak) Cognome, Nome...)',
		'listFieldHeader_publishers' => 'Editore',
		'listFieldHeader_publishers_ext' => 'Editori esterni (Cognome, Nome (LineBreak) Cognome, Nome...)',
		'listFieldHeader_title' => 'Titolo',
		'listFieldHeader_location' => 'Luogo',
		'listFieldHeader_run' => 'Edizione',
		'listFieldHeader_year' => 'Anno di pubblicazione',
		'listFieldHeader_volume' => 'Titolo e volume',
		'listFieldHeader_magazine_title' => 'Titolo della rivista',
		'listFieldHeader_magazine_year' => 'Anno della rivista',
		'listFieldHeader_magazine_issue' => 'Argomento della rivista',
		'listFieldHeader_anthology_title' => 'Titolo della raccolta',
		'listFieldHeader_anthology_publisher' => 'Editore della raccolta',
		'listFieldHeader_pages' => 'Pagine',
		'listFieldHeader_event_date' => 'Evento/Data',
		'listFieldHeader_other_redaction' => 'Altre redazioni',
		'list_mode_1' => 'Modalite 1',
		'list_mode_2' => 'Modalite 2',
		'list_mode_3' => 'Modalite 3',
		'back' => 'Indietro',
		'pi_list_browseresults_prev' => '< Indietro',
		'pi_list_browseresults_page' => '',
		'pi_list_browseresults_next' => 'Prossima >',
		'pi_list_browseresults_displays' => 'Mostra risultati ###FROM###-###TO### di ###OUT_OF### publicazioni',
		'pi_list_searchBox_search' => 'Ricerca',
		'pi_list_browseresults_first' => '<< Inizio',
		'pi_list_browseresults_last' => 'Fine >>',
		'editRecord' => '<img src="fileadmin/histsem/_templates/images/icon_edit.gif" height="9" width="9"> Adattare',
		'removeRecord' => '<img src="fileadmin/histsem/_templates/images/icon_delete.gif" height="9" width="9"> Cancellare',
		'pdfLinkText' => 'Scarica la Lista nel formato PDF',
		'txtLinkText' => 'Scarica la Lista nel formato RTF',
		'createPublication' => 'Crea pubblicazione',
		'noResultFound' => 'Non sono stati trovati risultati per la vostra richiesta',
		'searchLabel' => 'Ricerca',
		'publicationLabel' => 'Tipo di pubblicazione:',
		'allLabel' => 'Tutti',
		'titleLabel' => 'Titolo:',
		'authorLabel' => 'Autore:',
		'publYearLabel' => 'Anno di pubblicazione:',
		'fromLabel' => 'da:',
		'toLabel' => 'a:',
		'pubLanguageLabel' => 'Lingua: ',
	),
);
?>